-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE TABLE IF NOT EXISTS public.shifts (
    company character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    shift_length INTERVAL NOT NULL,
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    start_time time WITH time zone NOT NULL,
    description character varying COLLATE pg_catalog."default",
    pay_rate character varying COLLATE pg_catalog."default",
    active boolean NOT NULL DEFAULT TRUE,
    employee_id uuid,
    company_id uuid,
    CONSTRAINT shifts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
) TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.shifts OWNER TO postgres;

ALTER TABLE IF EXISTS public.shifts ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.shifts TO anon;

GRANT ALL ON TABLE public.shifts TO authenticated;

GRANT ALL ON TABLE public.shifts TO postgres;

GRANT ALL ON TABLE public.shifts TO service_role;

COMMENT ON TABLE public.shifts IS 'shift info';

COMMENT ON COLUMN public.shifts.active IS 'post active based on availability, start date + time';

COMMENT ON COLUMN public.shifts.employee_id IS 'linked employee who is working the shift';

COMMENT ON COLUMN public.shifts.company_id IS 'company that made the post';

CREATE POLICY "Public posts are viewable by everyone." ON public.shifts AS PERMISSIVE FOR
SELECT TO public USING (TRUE);

CREATE POLICY "Public posts can be updated by anyone." ON public.shifts AS PERMISSIVE FOR
UPDATE TO public USING (
        (
            (active = TRUE)
            AND (employee_id IS NULL)
        )
    ) WITH CHECK (TRUE);

DROP TABLE IF EXISTS public.posts CASCADE;