-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS trigger
    LANGUAGE 'plpgsql'
    VOLATILE SECURITY DEFINER
    COST 100
AS $BODY$
 BEGIN
INSERT INTO public.users (id, email)
VALUES (new.id, new.email);

RETURN new;

END;

$BODY$;

CREATE POLICY "Public posts can be updated by anyone."
    ON public.posts
    AS PERMISSIVE
    FOR UPDATE
    TO public
    USING (((active = true) AND (employee_id IS NULL)))
    WITH CHECK (((active = true) AND (employee_id IS NULL)));


DROP POLICY IF EXISTS "Public posts can be updated by authenticated users." ON public.posts;
