-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
ALTER TABLE public.users
ALTER COLUMN email TYPE character varying COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.users
ALTER COLUMN email
SET STORAGE EXTENDED;

ALTER TABLE IF EXISTS public.companies
ALTER COLUMN company_name
SET NOT NULL;

ALTER TABLE IF EXISTS public.posts ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.posts
FROM authenticated;

REVOKE ALL ON TABLE public.posts
FROM postgres;

REVOKE ALL ON TABLE public.posts
FROM service_role;

GRANT ALL ON TABLE public.posts TO authenticated;

GRANT ALL ON TABLE public.posts TO service_role;

GRANT ALL ON TABLE public.posts TO postgres;

ALTER TABLE public.posts
ALTER COLUMN description TYPE character varying COLLATE pg_catalog."default";

ALTER TABLE public.posts
ALTER COLUMN pay_rate TYPE character varying COLLATE pg_catalog."default";

ALTER TABLE IF EXISTS public.posts
ALTER COLUMN company_id
SET STORAGE PLAIN;

COMMENT ON COLUMN public.posts.company_id IS 'company that made the post';