-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.posts
    DISABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.posts FROM anon;
REVOKE ALL ON TABLE public.posts FROM authenticated;
REVOKE ALL ON TABLE public.posts FROM postgres;
REVOKE ALL ON TABLE public.posts FROM service_role;
GRANT ALL ON TABLE public.posts TO anon;

GRANT ALL ON TABLE public.posts TO authenticated;

GRANT ALL ON TABLE public.posts TO postgres;

GRANT ALL ON TABLE public.posts TO service_role;

ALTER TABLE IF EXISTS public.companies
    ALTER COLUMN company_name DROP NOT NULL;
